# Generated by Django 4.2.4 on 2023-08-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
