# Generated by Django 4.2.4 on 2023-08-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='pay_link',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
