# Generated by Django 4.2.4 on 2023-08-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_alter_factor_pay_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='pay_link',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
