# Generated by Django 4.2.4 on 2023-08-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_alter_factor_pay_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='pay_link',
            field=models.CharField(blank=True),
        ),
    ]
