# Generated by Django 4.2.4 on 2023-08-28 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_alter_factor_pay_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='from_u',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_u', to='card.card'),
        ),
    ]
