# Generated by Django 4.2.4 on 2023-08-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0009_factor_from_u'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='balance',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
