# Generated by Django 4.2.4 on 2023-09-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0011_factor_payed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='payed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
