# Generated by Django 4.2.4 on 2023-11-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0013_alter_factor_pay_link_alter_factor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='status',
            field=models.CharField(choices=[('N', 'not paid'), ('P', 'paid')], default='N', max_length=500),
        ),
    ]
