# Generated by Django 4.2.4 on 2023-08-22 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_myuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
