# Generated by Django 4.2.4 on 2023-08-24 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_temp_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_token',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
