# Generated by Django 4.2.4 on 2023-10-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_myuser_created_date_alter_myuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_token',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
