# Generated by Django 4.2.4 on 2023-10-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_temp_token_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_token',
            name='token',
            field=models.UUIDField(),
        ),
    ]
